print('=======================================')
print("= QueAreTee's message encoder/decoder =")
print('=======================================')
while 1==1:
    choice = input("Would you like to encode or decode some text? ")
    if choice == 'encode' or choice == 'Encode' or choice == '1':
        print('You have chosen to encode some text.')
        choice2 = str(input('Please enter the text you would like to encode (use lowercase letters, no numbers): '))
        one = str.replace(choice2, 'a', '1')
        two = str.replace(one , 'b' , '2')
        three = str.replace(two , 'c', '3')
        four = str.replace(three , 'd', '4')
        five = str.replace(four , 'e', '5')
        six = str.replace(five , 'f', '6')
        seven = str.replace(six , 'g' , '7')
        eight = str.replace(seven, 'h', '8')
        nine = str.replace(eight , 'i', '9')
        ten = str.replace(nine , 'j', '/')
        eleven = str.replace(ten, 'k', '!')
        twelve = str.replace(eleven, 'l', '@')
        thirteen = str.replace(twelve, 'm', '#')
        fourteen = str.replace(thirteen, 'n', '$')
        fifteen = str.replace(fourteen, 'o', '%')
        sixteen = str.replace(fifteen, 'p', '+')
        seventeen = str.replace(sixteen, 'q', '&')
        eighteen = str.replace(seventeen, 'r', '*')
        nineteen = str.replace(eighteen, 's', '(')
        twenty = str.replace(nineteen, 't', ')')
        twentyone = str.replace(twenty, 'u', '=')
        twentytwo = str.replace(twentyone, 'v', '-')
        twentythree = str.replace(twentytwo, 'w', '`')
        twentyfour = str.replace(twentythree, 'x', '"')
        twentyfive = str.replace(twentyfour, 'y', ':')
        twentysix = str.replace(twentyfive, 'z', ';')
        twentyseven = str.replace(twentysix, ' ', '^')
        print("Here is your encoded message: ", twentyseven)
        print('\n')
    elif choice == "decode" or choice == "Decode" or choice == "2":
        print('You have chosen to decode some text.')
        choice2 = str(input('Please enter the text you would like to decode: '))
        one = str.replace(choice2, '1', 'a')
        two = str.replace(one , '2', 'b')
        three = str.replace(two , '3', 'c')
        four = str.replace(three , '4', 'd')
        five = str.replace(four , '5', 'e')
        six = str.replace(five , '6', 'f')
        seven = str.replace(six , '7' , 'g')
        eight = str.replace(seven, '8', 'h')
        nine = str.replace(eight , '9', 'i')
        ten = str.replace(nine , '/', 'j')
        eleven = str.replace(ten, '!', 'k')
        twelve = str.replace(eleven, '@', 'l')
        thirteen = str.replace(twelve, '#', 'm')
        fourteen = str.replace(thirteen, '$', 'n')
        fifteen = str.replace(fourteen, '%', 'o')
        sixteen = str.replace(fifteen, '+', 'p')
        seventeen = str.replace(sixteen, '&', 'q')
        eighteen = str.replace(seventeen, '*', 'r')
        nineteen = str.replace(eighteen, '(', 's')
        twenty = str.replace(nineteen, ')', 't')
        twentyone = str.replace(twenty, '=', 'u')
        twentytwo = str.replace(twentyone, '-', 'v')
        twentythree = str.replace(twentytwo, '`', 'w')
        twentyfour = str.replace(twentythree, '"', 'x')
        twentyfive = str.replace(twentyfour, ':', 'y')
        twentysix = str.replace(twentyfive, ';', 'z')
        twentyseven = str.replace(twentysix, '^', ' ')
        print('Your decoded message is:', twentyseven)
        print('\n')
    else:
        print('That is not an option. Please choose either decode or encode.')
        print('\n')
